### ISSUE TITLE
DocumentReader.Instance().Init(MainActivity.this, license) returns false

### ISSUE THREAD

**Issue by efredz** [regulaforensics/RegulaDocumentReader-Android#1]
I've generated a demo license with the package for our demo application, copied the license to the specified location (res/raw/regula.license), the file is read correctly but after checking the license:

    bool validLicense = DocumentReader.Instance().Init(InCapture.this, license)

The method returns false, what else should I check?

**Comment by mskvorcovs** [comment]
Hi,

The license should be matching applicationId, not the package name. Please, check you applicationId inside build.gradle file. It should look like this:

```
defaultConfig {
        applicationId "your.app.id"
        minSdkVersion 14
        targetSdkVersion 25

        versionCode 1
        versionName "1.0"
    }
```

If this is ok, please, send us your logcat output.

**Comment by efredz** [comment]
I used my package name to generate the license, but there was a mismatch between my applicationId and the package name. Fixed that and now everything is working.
