### ISSUE TITLE
Passports from certain countries can't be read

### ISSUE THREAD

**Issue by efredz** [regulaforensics/RegulaDocumentReader-Android#3]
We've been testing your SDK and we've found that the Intent can't read passports from certain countries.
In this [http://imgur.com/a/9dZ6g](album) we uploaded the passports we've been using to test the SDK. The passports from the United States and Brazil can't be read (using your SDK or your demo application), when calling the Intent to read, nothing happens and the passport is not detected. The rest of the passports works OK.

**Comment by ikliashchou** [comment]
Your link is not valid, could you please use support@regulaforensics.com and send us the images in question?

There should be no issues with any of the mentioned documents.

**Comment by efredz** [comment]
[Here's the fixed link](http://imgur.com/a/9dZ6g).

**Comment by ikliashchou** [comment]
You have 3 images in your set that are not real docs, but artificial replicas, that are wrong in printing and filling (not according to ICAO 9303). 

We are targeting real documents with our solution, so I can suggest you remove these images from your set (Brasil, USA and Colombia) and replace them with correct specimens.

All other docs are read correctly, while most of them are expired.
